### ISSUE TITLE
wrong signing key?

### ISSUE THREAD

**Issue by IzzySoft** [lotusprey/otraku#101]
The signing key used by v1.2.5 does not match the one used before. Previous signature:

```
Signer #1 certificate DN: CN=Hristo Zhablyanov, OU=None, O=None, L=Sofia, ST=Bulgaria, C=BG
Signer #1 certificate SHA-256 digest: 180c1115b601e7e61d9243a0725281184edde348d9e68e72dd1912d312a2a0b9
Signer #1 certificate SHA-1 digest: 9fb735d9b3b391c5eedb6e04eb639a90c82c994b
Signer #1 certificate MD5 digest: 38270444829b76eba0264d1104966c5d
```

current signature:

```
Signer #1 certificate DN: CN=Hristo Zhablyanov
Signer #1 certificate SHA-256 digest: c457425b3509ff88b9c8bf6d5b0c9e48bbde9b96c3f2af7570321a211a803e12
Signer #1 certificate SHA-1 digest: 09477f176f6e9d123289ed838aa750defee3181e
Signer #1 certificate MD5 digest: fad99089aac616bfb97a65a80313d229
```

May I ask what happened? A changed signing key makes it impossible to update, one has to uninstall and reinstall the app while losing all its data.

**Comment by lotusprey** [comment]
Yeah, sorry about that. I messed up a bit and had to change the key 🙃. Setting the new key on google play doesn't cause any problems, when updating the app from there, but I didn't consider the problems it would cause on other platforms. Either way, that would be the key used from here on out; sorry again for the inconvenience.

**Comment by IzzySoft** [comment]
Thanks for your fast reply!

What mess would force the change of a signing key? :thinking:

Do you still have the old one and could provide an APK from the latest release signed with that (e.g. attaching it here), to prove it's really you? Don't get me wrong, but someone having hacked your account would (hopefully) not have access to that previous key, which would then be the reason for the changed key, so that would prove it's really you.

Further I wonder why the `CN=` is incomplete with the new key while it was complete with the previous one, but that's a different question maybe :wink:

**Comment by lotusprey** [comment]
I just lost the old key when I reinstalled my system (it was supposed to be backed up, but... turned out it wasn't). I've confirmed the change of the key in the app's discord server, which gives what I'm saying here credibility, with the assumption that my discord and github account have not been hacked simultaneously 😅.
As far as why the rest of the certificate fields are empty, uugh, I don't really have any concrete explanation. I just decided it's not a problem if I don't fill any more personal information...

**Comment by lotusprey** [comment]
Oh, in case you want to confirm the discord thing, here's the invite in the code: https://github.com/lotusprey/otraku/blob/87d3fc4b9d76060d90f2ae247f4263977cf5637f/lib/modules/settings/settings_about_tab.dart#L51C81-L51C81
And then this message fore example:
https://discord.com/channels/831837003754373171/831839095550246923/1146888899361263686

**Comment by IzzySoft** [comment]
Thanks for the explanation! And sorry, I'm not using Discord.

So you will stick to the current key then? A hint in the release notes would be good then, as those having the previous version installed might otherwise be confused why the update fails.

**Comment by lotusprey** [comment]
Hahah, yeah, I really hope I can stick to this key 😄.
Thanks for the heads up, I will update the release notes!

**Comment by IzzySoft** [comment]
Thanks! Then I'll remove all previous versions in my repo, list the new one and pin the new sig hash now… Done, effective with the next sync around 6 pm UTC. Take good care for your new key, ideally have a backup off-device (e.g. on an encrypted thumb drive) :wink:

PS: Might be a good idea to establish Fastlane structures here (be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance with that). Then you could a.o. point out such things via "per-release changelogs", which (at least with the official F-Droid client and on the website) are shown right next to the app description, so folks are aware. It also allows you to control how your app is presented: my updater would fetch changes along with releases then.

**Comment by IzzySoft** [comment]
PS: as for your `full_description.txt` in Fastlane, which is currently set to be skipped by my updater (as until recently it was just a "stub"), maybe you can adjust the formatting a little? If you'd insert an empty line before and after the bullet-point list, it would be proper "standard Markdown" and could be rendered as such by my framework, which would look much better than just having each newline replaced by a `<br>` :wink: If you let me know here, I'll check again and see that I can enable it on my end accordingly. Thanks!

**Comment by IzzySoft** [comment]
@lotusprey ^^ just in case my ping didn't reach you – and in answer to your mail :wink:

**Comment by IzzySoft** [comment]
My updater pulls from HEAD, so no extra release needed. Just let me know when it's been pushed, I'd then cross-check, update the config here, and if you wish trigger a pull.

**Comment by IzzySoft** [comment]
> Ok, I think you can pull now

Done, should show up with the next sync around 7 pm UTC then, thanks!

> Tell me if there's something else to do.

![image](https://github.com/lotusprey/otraku/assets/6781438/134915a1-4993-49d4-9a16-44b767a25a1b)

Easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by IzzySoft** [comment]
Oopsie – another notification that didn't reach my inbox (happens not only to me that part of them get lost)…

Bundle setting does not affect my repo. So if you want to keep the blob in there, well… I don't think it's needed, but if the proprietary store requires it you can keep it in there, yes.
