### ISSUE TITLE
Can't log into the account after getting authentication in the browser

### ISSUE THREAD

**Issue by Gukkey** [lotusprey/otraku#105]
Version: v.1.2.6+1

The login is not happening after getting the authentication in the browser. I tried to log into the "Primary Account" but after getting authenticated in the browser instead of logging in, the app just cuts off the redirect and comes back to the square one. Tried authenticating and logging in multiple times but it just cuts off after getting authentication in the browser.

**Comment by lotusprey** [comment]
From what I've gathered, this is not an Otraku problem. There is an issue with AniList third-party authentication in a few countries right now. I believe there's a discussion on their Discord server; I hope it gets resolved soon.

**Comment by Gukkey** [comment]
It works when we use VPN. Same solution for for any kind of error inside the app too.
