### ISSUE TITLE
Support for opening anilist links directly on the app

### ISSUE THREAD

**Issue by lewdpatriot** [lotusprey/otraku#110]
Is it possible to make the app open external anilist links directly on the app? (instead of opening in a browser tab?)
![Screenshot_2023-10-27-14-20-07-09_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/lotusprey/otraku/assets/63286528/97c65335-9844-433b-85f8-b38ef0db87cb)

**Comment by nstrelow** [comment]
I had a very quick look at this one.

There is quite a detailed guide: https://docs.flutter.dev/ui/navigation/deep-linking

But it isn't super easy.

I haven't really dived into the code base, but it highly depends on how routing is handled inside the app.

**Comment by lotusprey** [comment]
I actually have something to say on this issue, but I had forgotten about it 🤡
I'm currently reworking how the navigation is handled in the whole app (on a local branch). After finishing that, it should be easier for me to implement deep linking, so hopefully it will be ready for the next update (no ETA for when that will happen).

**Comment by lotusprey** [comment]
The new update is capable of handling deep links on android. There are some limitations though - if you set Otraku as the default for anilist.co links, trying to redirect to such an AniList link from the app won't work and Otraku will take over it. This will need some fixing, but that's another topic.
Also, while normal media links work, if the title at the end is skipped, Otraku won't handle it properly, but that is an easy fix and will be corrected in the next release.
Either way, I'm closing this for now.

**Comment by ProchyGaming** [comment]
Hello has this been fixed? Because whenever I open the link in otraku the anime opens properly, but it's stuck in a refresh loop until eventually the error 429 shows up. Thanks

**Comment by Pr0chy** [comment]
> That must be some bug separate from this issue. I will try reproducing what you mentioned when I have time @Pr0chy 

In that case I'll try to provide as much info about my environment as I can 
Android 14
Pixel 7
Firefox
Latest version of otraku
To replicate this issue: 
0. Register the link in apps settings
1. Go to any anime anilist URL for [https://anilist.co/anime/136804/Kono-Subarashii-Sekai-ni-Shukufuku-wo-3/](example)
2. In the Firefox menu choose open in app
