### ISSUE TITLE
[Feature Request] Ability to turn off "Feed" Tab

### ISSUE THREAD

**Issue by zerobun** [lotusprey/otraku#128]
As the title says, it's to have the ability to turn off feeds, I personally and I assume a lot of people might just like to use the app for tracking their anime/manga. 
Nothing major but would be nice to have as an option to be able to turn feeds off.

**Comment by lotusprey** [comment]
This will not be added - you can already configure the default home tab and the feed tab is lazy-loaded, so it won't even use up data if you don't open it.
