### ISSUE TITLE
Sorting Anime list does not stick when restarting the app.

### ISSUE THREAD

**Issue by cospking** [lotusprey/otraku#169]
Hello,

I'm trying to sort the Anime list to show **Last Updated** on top as I use practically all apps like this, but unfortunately it doesn't stick to the setting on:
1.4.2
1.4.3
1.5.2

Not sure if it happens on older versions as I've only been using the app since 1.4.2.,...

**Device:** Samsung Galaxy S24 Ultra
**Android version:** 14

**Default sortings:**
![photo_2024-09-23_15-50-00](https://github.com/user-attachments/assets/ce2e34aa-8f48-4d80-ba70-15f79e055fe1)

**Manga sorting seems fine:**
![photo_2024-09-23_15-50-02](https://github.com/user-attachments/assets/24868cbb-0ca7-457a-93b5-baf5e0dc031f)

**If I set it to Last Updated it will reset to Airing after restarting the app:**
![image](https://github.com/user-attachments/assets/fbbe5639-173d-4e09-be6c-4ddc218838c9)

**Anime sorting keeps reset to Airing after restarting app:**
![qView_LJ5ecSyt1D](https://github.com/user-attachments/assets/2e1ffbd6-41cd-491b-a8d7-42df5add45c6)

**Comment by lotusprey** [comment]
This is not a bug, but a feature - in the collection previews subsection disable exclusive airing sort for anime preview. The idea is that previews only contain your current anime, and people often want to see those according to what's airing next.
