### ISSUE TITLE
Got someone else's notifications? 

### ISSUE THREAD

**Issue by LadyHaywood** [lotusprey/otraku#175]
Wish I recorded it, but I just got a string of push notifications about updates for anime that wasn't connected to anything I had on my list. So I checked the app itself and I was still signed in me but the notifications where duplicating those anime shows. I went to the home dash, went back into the notifications, and saw a completely different set of people reacting to another user's post. I was seeing this one user's notifications and then the app crashed... And now it's back to normal?

While writing this, I just got another push notification about something being added to the site but when I open the app it's not there in my notification list.

**Comment by lotusprey** [comment]
Have you checked what the notifications on AniList were? It's basically impossible that Otraku will show notifications for something that it hasn't received from the API, so maybe that's an API bug.

**Comment by lotusprey** [comment]
Also maybe [this](https://anilist.co/forum/thread/3878/comment/2778530) is related, but I don't know

**Comment by LadyHaywood** [comment]
Sadly, I don't have an image of them in otraku. I can only show you my phone's notification history when they showed up. I don't think it'll help anything, I thought it was weird when I got these and then saw my in app notifications were somebody else's. 
![Screenshot_20241118_075242_Settings](https://github.com/user-attachments/assets/fc73dd62-d25e-4b22-981a-2d7fb5fca86f)

**Comment by lotusprey** [comment]
Yeah, I saw other comments on reddit and it seems this really was an API issue unrelated to Otraku. That's why I closed it.
