### ISSUE TITLE
Slow loading of feed when Messages checkbox is checked.

### ISSUE THREAD

**Issue by cynide4869** [lotusprey/otraku#179]
The home feed takes more time to load, or doesn't load at all (times out) when the Messages checkbox is checked. If I don't select the checkbox for Messages, it loads instantly. Observed this before v1.6 and even now it persists.

![Feed Page](https://github.com/user-attachments/assets/af119ec4-e2c0-40e4-8ff3-571968682c51)

**Comment by lotusprey** [comment]
This is most probably an AniList problem, not an Otraku one. AniList doesn't usually show messages on the home feed, so while their API allows for that, the feature is likely not optimized/cached. I still keep the option in case it works for people, but I can't do anything about the slow loading times.

**Comment by cynide4869** [comment]
Oh that makes sense, gotcha.
