### ISSUE TITLE
External/Streaming Links

### ISSUE THREAD

**Issue by YouSummoner** [lotusprey/otraku#62]
If possible, please add External And Streaming Links in the anime info page form Anilist.
![Screenshot_20221116-201946_Kiwi Browser.png](https://user-images.githubusercontent.com/107224555/202212982-334a88e1-3aff-499b-83ae-a7e14ae3137c.png)

**Comment by lotusgate** [comment]
Yep, this is planned.

**Comment by crxssed7** [comment]
Can I take this one? I can start on it this weekend if so.

**Comment by lotusgate** [comment]
Sure, what are you planning to do? I imagine the links looking the same as the genres/tags/studios, i.e. a horizontal list of chips with the name of the site the link points to.
If I remember correctly, AL provided appropriate accent color for which site, which can be applied to the background of the chip. However, I'm not sure how well it would look in the context of Otraku. I guess it's something that should be checked out...

**Comment by crxssed7** [comment]
> Sure, what are you planning to do? I imagine the links looking the same as the genres/tags/studios, i.e. a horizontal list of chips with the name of the site the link points to. If I remember correctly, AL provided appropriate accent color for which site, which can be applied to the background of the chip. However, I'm not sure how well it would look in the context of Otraku. I guess it's something that should be checked out...

Yes I was thinking something similar to the genres/tags section. As for the colours, I'll have to play around with it to see if they fit.
