### ISSUE TITLE
My activities in Feed

### ISSUE THREAD

**Issue by Megaatroon** [lotusprey/otraku#88]
I have to set it every time i open the app in the previous versions this doesn't happen.![image](https://github.com/lotusprey/otraku/assets/86772939/f233cea9-af30-4679-a364-7dfe371e1fc5)

**Comment by lotusprey** [comment]
Hi, this was a bug in 1.2.4, but in 1.2.4+1 the setting should be remembered by the app every time you change it. Are you sure you're on the newest version?
