### ISSUE TITLE
Add Support for Monochrome Icon Color Change in Android 13

### ISSUE THREAD

**Issue by Nadim147c** [lotusprey/otraku#89]
Android 13 has this awesome new feature that lets users change app icons to match their theme color. But Otraku doesn't support monochrome icons for color changes yet.

It'll be great if Otraku add support for that.

**Comment by dlsf** [comment]
Are you sure that you're using the latest version of Otraku? The themed icons are working for me

**Comment by Nadim147c** [comment]
Sorry for not checking the version from release tab. I checked Play store and droid-ify but there wasn't any update option. Play store has the latest version but for some reason it didn't show option for update.

**Comment by lotusprey** [comment]
Yeah, unfortunately, the playstore is sometimes slow to show new releases and requires you to go to the app's page, if you want to get the update early enough.
