### ISSUE TITLE
Don't auto focus keyboard/search on back action

### ISSUE THREAD

**Issue by Burgess101** [lotusprey/otraku#90]
Hi,

Love the app, just a small quibble. 

When discovering anime/manga entering a title then going back will auto focus the search bar, bringing the keyboard up. This means every time I want to view something and come back out I have to minimise the keyboard. It's quite irritating. 

Hopefully that makes sense, keep up the good work!

**Comment by lotusprey** [comment]
Hi,
if the keyboard is revealed when you open a media, then it will also appear when you close the media page. However, if you've closed the keyboard by pressing enter, it will stay closed when you pop the media page. I find this consistent and hadn't thought of it as a problem until now. I guess I will have to think about whether always keeping the keyboard closed, after you go back, is optimal.

**Comment by Burgess101** [comment]
Ah I see how it works now. Thank you!
