### ISSUE TITLE
Show user status in the "related" section of the media page

### ISSUE THREAD

**Issue by l2eused** [lotusprey/otraku#98]
Show current user activity (i.e Planning, Watching) in Related page same as Discover page

Related page
![Screenshot_20230822-224816.png](https://github.com/lotusprey/otraku/assets/94383254/4dadd39d-0d0d-4e9c-a1a7-3d3d7dbf0af8)

Discover page
![Screenshot_20230822-224826_Otraku_1.png](https://github.com/lotusprey/otraku/assets/94383254/1e45daf6-e638-4169-a9b4-b89fe70e3117)

**Comment by lotusprey** [comment]
Closing this as resolved in version 1.2.7, for which there's currently a pre-release, but the official release will be out soon.
